version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - bash codebuild/template-validation.sh

  build:
    commands:
      - bash codebuild/build.sh

artifacts:
  files:
    - cloudformation/serverless.yaml
    - cloudformation/configuration.json
